baseURL = "https://kalimawiki-preview.vercel.app/"
languageCode = "en-us"
title = "Kalima Wiki"
theme = "PaperMod"
paginate = 10

[params]
  defaultTheme = "auto" # auto, dark, light
  showReadingTime = true
  showShareButtons = true
  showPostNavLinks = true
  showBreadCrumbs = true
  showCodeCopyButtons = true
  showFullTextinRSS = false
  showPostsOnHomePage = true
  ShowPostNavLinks = true
  showTags = true

  [params.homeInfoParams]
    Title = "Welcome to Kalima Wiki"
    Content = "Your AI-powered source for pharmaceutical industry insights — exploring the future of drug discovery and healthcare."

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/contact/"
  weight = 4
 
[pagination]
  pagerSize = 5

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
